openapi: 3.2.0
info:
  description: Javascript client to remove the PCI burden when taking payments online
  title: Connect-E Development Environment Payment Methods API
  version: 1.0.0
servers:
- url: https://e.test.connect.paymentsense.cloud
tags:
- name: Payment Methods
paths:
  /v1/payment-methods:
    get:
      description: Get supported payment methods for authenticated merchant.
      tags:
      - Payment Methods
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentMethods'
        '500':
          description: Internal Server Error
components:
  schemas:
    paymentMethods:
      type: object
      properties:
        cardSchemes:
          description: List of card schemes supported for this merchant. Supported values are <code>VISA</code>, <code>MASTERCARD</code>, <code>MAESTRO</code>, <code>AMEX</code>, <code>DCI</code>, <code>DISCOVER</code>.
          type: array
          items:
            type: string
          example:
          - VISA
          - MASTERCARD
          - MAESTRO
          - AMEX
        wallets:
          description: List of payment wallets supported for this merchant. Supported values are <code>APPLE_PAY</code>, <code>GOOGLE_PAY</code>.
          type: array
          items:
            type: string
          example:
          - APPLE_PAY
          - GOOGLE_PAY
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
    access_token:
      type: apiKey
      in: header
      name: Authorization
      description: This authorization is deprecated and only used on the POST /v1/cross-reference-payments endpoint. Please only use the api_key for new integrations.
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
