openapi: 3.2.0
info:
  description: Javascript client to remove the PCI burden when taking payments online
  title: Connect-E Development Environment Cross Reference Payment API
  version: 1.0.0
servers:
- url: https://e.test.connect.paymentsense.cloud
tags:
- name: Cross Reference Payment
paths:
  /v1/cross-reference-payments/{access-token}:
    post:
      description: Execute a transaction using the cross reference from a previous transaction. To execute this request, pass the id from creating an access token as {access-token} in the path. This token can only be used once.
      tags:
      - Cross Reference Payment
      operationId: /v1/cross-reference-payments/access-token
      responses:
        '200':
          description: Payment Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/crossReferenceResponse'
        '400':
          description: Bad Request - The request has failed validation by our servers.
        '401':
          description: Unauthorized - There is an issue authenticating the request.
        '500':
          description: Internal Server Error - An error has occured while processing the request.
      parameters:
      - description: Id returned from creating an access-token for the payment
        in: path
        name: access-token
        required: true
        example: WEV2IGFzt-yOb1bAQFv5gByq38zz1OdMdyvIXHHJdn7CRzBrdd9VZJNdwhAKMW0b-ar6KDJMFivr6NlKiimxljV6kXDC2pCAVoJT6SoEP5GzrmwvPg6EIe7FKE2Bn83HHkd8S4pxSrksSCl6cg==
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/paymentCrossReferenceRequest'
      security:
      - jwt: []
components:
  schemas:
    paymentCrossReferenceRequest:
      type: object
      properties:
        crossReference:
          type: string
          example: '181025085937854101886353'
        cv2:
          type: string
          description: The CV2 code associated with the card from the original transaction. Note that if using this you need to be PCI SAQ-D compliant
          example: '123'
      required:
      - crossReference
    crossReferenceResponse:
      type: object
      properties:
        statusCode:
          type: integer
          enum:
          - 0
          - 4
          - 5
          - 20
          - 30
          example: 0
          description: "* `0` - Successful\n* `4` - Referred\n* `5` - Declined\n* `20` - Duplicate Transaction\n* `30` - Failed\n\n More details <a href='/ConnectE/Standard#statusCode'>here</a>"
        authCode:
          type: string
          example: '866344'
        message:
          type: string
          example: 'AuthCode: 898968'
  requestBodies:
    paymentCrossReferenceRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/paymentCrossReferenceRequest'
      description: Details of the Payment to be made
      required: true
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
    access_token:
      type: apiKey
      in: header
      name: Authorization
      description: This authorization is deprecated and only used on the POST /v1/cross-reference-payments endpoint. Please only use the api_key for new integrations.
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
